module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Browser
import Examples
import Expect
import Html
import Html.Attributes
import Html.Events
import Platform.Cmd
import Platform.Sub
import Test
import Yafl


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Yafl.Widget String.String String.String String.String
                            unused =
                                stringWidget__Readme_0
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        let
                            unused : Yafl.Widget Basics.Bool Basics.Bool Basics.Bool
                            unused =
                                boolWidget__Readme_0
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 1"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused :
                                { string :
                                    Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                                , bool :
                                    Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId Basics.Bool Basics.Bool
                                }
                            unused =
                                Examples.fields
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 2"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                            unused =
                                Examples.nonEmptyString
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                            unused =
                                Examples.firstName
                        in
                        Expect.pass
                    )
                , Test.test
                    "2"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                            unused =
                                Examples.lastName
                        in
                        Expect.pass
                    )
                , Test.test
                    "3"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId Basics.Bool Basics.Bool
                            unused =
                                Examples.isAdmin
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 3"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId Basics.Never Examples.User
                            unused =
                                Examples.user
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 4"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Platform.Program () (Yafl.Model Examples.FormModel) (Yafl.Msg Examples.FormMsg)
                            unused =
                                main__Readme_4
                        in
                        Expect.pass
                    )
                ]
            ]
        , Test.describe
            "Yafl"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : ( Yafl.Model Examples.FormModel, Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg) )
                                unused =
                                    init__Yafl__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            let
                                unused : List (Html.Html (Yafl.Msg Examples.FormMsg))
                                unused =
                                    Yafl.view
                                        form__Yafl__Header_0
                                        model__Yafl__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "2"
                        (\() ->
                            let
                                unused : Platform.Sub.Sub (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.subscriptions
                                        form__Yafl__Header_0
                                        model__Yafl__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "3"
                        (\() ->
                            Yafl.submit
                                form__Yafl__Header_0
                                model__Yafl__Header_0
                                |> Expect.equal (Result.Ok Basics.False)
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                myCustomTypeField__Yafl__Header_1
                                model__Yafl__Header_1
                                |> Expect.equal
                                    (Result.Ok (Foo__Yafl__Header_1 ""))
                        )
                    ]
                ]
            , Test.describe
                "andMap"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__andMap_0
                                model__Yafl__andMap_0
                                |> Expect.equal
                                    (Result.Ok
                                        { firstName = ""
                                        , middleName = ""
                                        , lastName = ""
                                        }
                                    )
                        )
                    ]
                ]
            , Test.describe
                "andSelectField"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            modelAndCmd__Yafl__andSelectField_0
                                |> Tuple.first
                                |> Yafl.submit
                                    myChoiceField__Yafl__andSelectField_0
                                |> Expect.equal
                                    (Result.Err
                                        [ ( "0.0", "Oh no, you failed!" ) ]
                                    )
                        )
                    , Test.test
                        "1"
                        (\() ->
                            modelAndCmd__Yafl__andSelectField_0
                                |> Yafl.andSelectField
                                    myAddressedField__Yafl__andSelectField_0
                                |> Tuple.first
                                |> Yafl.submit
                                    myChoiceField__Yafl__andSelectField_0
                                |> Expect.equal (Result.Ok "Hurrah!")
                        )
                    ]
                ]
            , Test.describe
                "andThen"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                                unused =
                                    Examples.fields.string
                                        |> Yafl.label
                                            "Enter the first name of a Beatle"
                                        |> Yafl.andThen
                                            (\name ->
                                                if
                                                    List.member
                                                        name
                                                        [ "John"
                                                        , "Paul"
                                                        , "George"
                                                        , "Ringo"
                                                        ]
                                                then
                                                    Yafl.succeed name

                                                else
                                                    Yafl.fail "Invalid Beatle"
                                            )
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                                unused =
                                    Examples.fields.string
                                        |> Yafl.label
                                            "What would you like to say?"
                                        |> Yafl.andThen
                                            (\words ->
                                                if words == "Hello" then
                                                    Examples.fields.string
                                                        |> Yafl.label
                                                            "Who are you saying 'Hello' to?"
                                                        |> Yafl.map
                                                            (\moreWords ->
                                                                words
                                                                    ++ " "
                                                                    ++ moreWords
                                                            )

                                                else
                                                    Yafl.succeed words
                                            )
                            in
                            Expect.pass
                        )
                    , Test.test
                        "2"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String Basics.Float
                                unused =
                                    Examples.fields.string
                                        |> Yafl.label
                                            "Enter a floating-point number"
                                        |> Yafl.andThen
                                            (\string ->
                                                case String.toFloat string of
                                                    Maybe.Just float ->
                                                        Yafl.succeed float

                                                    Maybe.Nothing ->
                                                        Yafl.fail
                                                            "That's not a valid float"
                                            )
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "andUpdateField"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                fooField__Yafl__andUpdateField_0
                                updatedModel__Yafl__andUpdateField_0
                                |> Expect.equal
                                    (Result.Ok
                                        (Foo__Yafl__andUpdateField_0
                                            "Hello"
                                            "World"
                                        )
                                    )
                        )
                    ]
                ]
            , Test.describe
                "fail"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit form__Yafl__fail_0 model__Yafl__fail_0
                                |> Expect.equal
                                    (Result.Err [ ( "0", "Oh dear!" ) ])
                        )
                    ]
                ]
            , Test.describe
                "id"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                                unused =
                                    myField__Yafl__id_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.HasId String.String String.String
                                unused =
                                    myFieldWithId__Yafl__id_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "2"
                        (\() ->
                            let
                                unused : Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.send myFieldWithId__Yafl__id_0 "Hello!"
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "init"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : ( Yafl.Model Examples.FormModel, Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg) )
                                unused =
                                    Examples.fields.bool |> Yafl.init
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "intercept"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused :
                                    Yafl.Msg Examples.FormMsg
                                    -> Maybe.Maybe String.String
                                unused =
                                    Yafl.intercept
                                        myAddressedField__Yafl__intercept_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "label"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String
                                unused =
                                    nameField__Yafl__label_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "map"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            fooField__Yafl__map_0
                                |> Yafl.init
                                |> Tuple.first
                                |> Yafl.submit fooField__Yafl__map_0
                                |> Expect.equal
                                    (Result.Ok (Foo__Yafl__map_0 ""))
                        )
                    ]
                ]
            , Test.describe
                "map2"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit form__Yafl__map2_0 model__Yafl__map2_0
                                |> Expect.equal (Result.Ok ( "", "" ))
                        )
                    ]
                ]
            , Test.describe
                "select"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.select holyGrail__Yafl__select_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "selectField"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            model__Yafl__selectField_0
                                |> Yafl.submit
                                    myChoiceField__Yafl__selectField_0
                                |> Expect.equal
                                    (Result.Err
                                        [ ( "0.0", "Oh no, you failed!" ) ]
                                    )
                        )
                    , Test.test
                        "1"
                        (\() ->
                            model__Yafl__selectField_0
                                |> Yafl.selectField
                                    myAddressedField__Yafl__selectField_0
                                |> Tuple.first
                                |> Yafl.submit
                                    myChoiceField__Yafl__selectField_0
                                |> Expect.equal (Result.Ok "Hurrah!")
                        )
                    ]
                ]
            , Test.describe
                "send"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.send
                                        myAddressedField__Yafl__send_0
                                        "Hello!"
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "submit"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__submit_0
                                model__Yafl__submit_0
                                |> Expect.equal (Result.Ok "")
                        )
                    ]
                ]
            , Test.describe
                "subscriptions"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Platform.Sub.Sub (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.subscriptions
                                        form__Yafl__subscriptions_0
                                        model__Yafl__subscriptions_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "succeed"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__succeed_0
                                model__Yafl__succeed_0
                                |> Expect.equal (Result.Ok "Hurrah!")
                        )
                    ]
                ]
            , Test.describe
                "updateField"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                fooField__Yafl__updateField_0
                                model__Yafl__updateField_0
                                |> Expect.equal
                                    (Result.Ok (Foo__Yafl__updateField_0 "" ""))
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Yafl.submit
                                fooField__Yafl__updateField_0
                                updatedModel__Yafl__updateField_0
                                |> Expect.equal
                                    (Result.Ok
                                        (Foo__Yafl__updateField_0 "Hello!" "")
                                    )
                        )
                    ]
                ]
            , Test.describe
                "view"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : List (Html.Html (Yafl.Msg Examples.FormMsg))
                                unused =
                                    Yafl.view
                                        form__Yafl__view_0
                                        model__Yafl__view_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        ]


stringWidget__Readme_0 =
    { init = ( "", Platform.Cmd.none )
    , update = \msg model -> ( msg, Platform.Cmd.none )
    , view =
        \{ label } model ->
            [ Html.label [ Html.Attributes.for label ] [ Html.text label ]
            , Html.input
                [ Html.Attributes.id label
                , Html.Attributes.type_ "text"
                , Html.Attributes.value model
                , Html.Events.onInput Basics.identity
                ]
                []
            ]
    , subscriptions = \model -> Platform.Sub.none
    , submit = \model -> Result.Ok model
    , label = "String"
    }


boolWidget__Readme_0 =
    { init = ( Basics.False, Platform.Cmd.none )
    , update = \msg model -> ( msg, Platform.Cmd.none )
    , view =
        \{ label } model ->
            [ Html.label [ Html.Attributes.for label ] [ Html.text label ]
            , Html.input
                [ Html.Attributes.id label
                , Html.Attributes.type_ "checkbox"
                , Html.Attributes.checked model
                , Html.Events.onCheck Basics.identity
                ]
                []
            ]
    , subscriptions = \model -> Platform.Sub.none
    , submit = \model -> Result.Ok model
    , label = "Bool"
    }


fields__Readme_1 =
    Yafl.defineFields (\string bool -> { string = string, bool = bool })
        |> Yafl.addWidget Examples.stringWidget
        |> Yafl.addWidget Examples.boolWidget
        |> Yafl.endFields


type alias FormModel__Readme_1 =
    ( Maybe.Maybe String.String, ( Maybe.Maybe Basics.Bool, () ) )


type alias FormMsg__Readme_1 =
    ( Maybe.Maybe String.String, ( Maybe.Maybe Basics.Bool, () ) )


nonEmptyString__Readme_2 =
    Examples.fields.string
        |> Yafl.andThen
            (\string ->
                if String.isEmpty string then
                    Yafl.fail "This field must not be blank"

                else
                    Yafl.succeed string
            )


firstName__Readme_2 =
    Examples.nonEmptyString |> Yafl.label "What is the user's first name?"


lastName__Readme_2 =
    Examples.nonEmptyString |> Yafl.label "What is the user's last name?"


isAdmin__Readme_2 =
    Examples.fields.bool |> Yafl.label "Is the user an admin?"


user__Readme_3 =
    Yafl.succeed Examples.User
        |> Yafl.andMap Examples.firstName
        |> Yafl.andMap Examples.lastName
        |> Yafl.andMap Examples.isAdmin


main__Readme_4 =
    Browser.element
        { init = \flags -> Yafl.init Examples.user
        , update = \msg model -> Yafl.update Examples.user msg model
        , view = \model -> Html.form [] (Yafl.view Examples.user model)
        , subscriptions = \model -> Yafl.subscriptions Examples.user model
        }


form__Yafl__Header_0 =
    Examples.fields.bool


init__Yafl__Header_0 =
    Yafl.init form__Yafl__Header_0


model__Yafl__Header_0 =
    Tuple.first init__Yafl__Header_0


type MyCustomType__Yafl__Header_1
    = Foo__Yafl__Header_1 String.String
    | Bar__Yafl__Header_1 Basics.Bool


myCustomTypeField__Yafl__Header_1 =
    Yafl.choice
        |> Yafl.option "Foo" fooField__Yafl__Header_1
        |> Yafl.option "Bar" barField__Yafl__Header_1


fooField__Yafl__Header_1 =
    Examples.fields.string |> Yafl.map Foo__Yafl__Header_1


barField__Yafl__Header_1 =
    Examples.fields.bool |> Yafl.map Bar__Yafl__Header_1


model__Yafl__Header_1 =
    myCustomTypeField__Yafl__Header_1 |> Yafl.init |> Tuple.first


form__Yafl__andMap_0 =
    Yafl.succeed (\a b c -> { firstName = a, middleName = b, lastName = c })
        |> Yafl.andMap (Examples.fields.string |> Yafl.label "First name")
        |> Yafl.andMap (Examples.fields.string |> Yafl.label "Middle name")
        |> Yafl.andMap (Examples.fields.string |> Yafl.label "Last name")


model__Yafl__andMap_0 =
    Yafl.init form__Yafl__andMap_0 |> Tuple.first


myAddressedField__Yafl__andSelectField_0 =
    Yafl.succeed "Hurrah!" |> Yafl.id "any-string-as-long-as-it's-unique"


myChoiceField__Yafl__andSelectField_0 =
    Yafl.choice
        |> Yafl.option "Don't pick me!" (Yafl.fail "Oh no, you failed!")
        |> Yafl.option "I'm the one!" myAddressedField__Yafl__andSelectField_0


modelAndCmd__Yafl__andSelectField_0 =
    myChoiceField__Yafl__andSelectField_0 |> Yafl.init


type Foo__Yafl__andUpdateField_0
    = Foo__Yafl__andUpdateField_0 String.String String.String


fooField__Yafl__andUpdateField_0 =
    Yafl.map2
        Foo__Yafl__andUpdateField_0
        firstField__Yafl__andUpdateField_0
        secondField__Yafl__andUpdateField_0


firstField__Yafl__andUpdateField_0 =
    Examples.fields.string |> Yafl.id "a-unique-string"


secondField__Yafl__andUpdateField_0 =
    Examples.fields.string |> Yafl.id "another-unique-string"


updatedModel__Yafl__andUpdateField_0 =
    fooField__Yafl__andUpdateField_0
        |> Yafl.init
        |> Yafl.andUpdateField firstField__Yafl__andUpdateField_0 "Hello"
        |> Yafl.andUpdateField secondField__Yafl__andUpdateField_0 "World"
        |> Tuple.first


form__Yafl__fail_0 =
    Yafl.fail "Oh dear!"


model__Yafl__fail_0 =
    form__Yafl__fail_0 |> Yafl.init |> Tuple.first


myField__Yafl__id_0 =
    Examples.fields.string


myFieldWithId__Yafl__id_0 =
    myField__Yafl__id_0 |> Yafl.id "any-string-as-long-as-it's-unique"


myAddressedField__Yafl__intercept_0 =
    Examples.fields.string |> Yafl.id "any-string-as-long-as-it's-unique"


nameField__Yafl__label_0 =
    Examples.fields.string |> Yafl.label "What is your name?"


type MyCustomType__Yafl__map_0
    = Foo__Yafl__map_0 String.String


fooField__Yafl__map_0 =
    Yafl.map Foo__Yafl__map_0 Examples.fields.string


form__Yafl__map2_0 =
    Yafl.map2 (\a b -> ( a, b )) Examples.fields.string Examples.fields.string


model__Yafl__map2_0 =
    Yafl.init form__Yafl__map2_0 |> Tuple.first


holyGrail__Yafl__select_0 =
    Examples.fields.string |> Yafl.id "any-string-as-long-as-it's-unique"


myChoiceField__Yafl__select_0 =
    Yafl.choice
        |> Yafl.option "Cup of a carpenter" holyGrail__Yafl__select_0
        |> Yafl.option "Fancy chalice" (Yafl.fail "You chose... poorly")


myAddressedField__Yafl__selectField_0 =
    Yafl.succeed "Hurrah!" |> Yafl.id "any-string-as-long-as-it's-unique"


myChoiceField__Yafl__selectField_0 =
    Yafl.choice
        |> Yafl.option "Don't pick me!" (Yafl.fail "Oh no, you failed!")
        |> Yafl.option "I'm the one!" myAddressedField__Yafl__selectField_0


model__Yafl__selectField_0 =
    myChoiceField__Yafl__selectField_0 |> Yafl.init |> Tuple.first


myAddressedField__Yafl__send_0 =
    Examples.fields.string |> Yafl.id "any-string-as-long-as-it's-unique"


form__Yafl__submit_0 =
    Examples.fields.string


model__Yafl__submit_0 =
    form__Yafl__submit_0 |> Yafl.init |> Tuple.first


form__Yafl__subscriptions_0 =
    Examples.fields.string


model__Yafl__subscriptions_0 =
    form__Yafl__subscriptions_0 |> Yafl.init |> Tuple.first


form__Yafl__succeed_0 =
    Yafl.succeed "Hurrah!"


model__Yafl__succeed_0 =
    form__Yafl__succeed_0 |> Yafl.init |> Tuple.first


type Foo__Yafl__updateField_0
    = Foo__Yafl__updateField_0 String.String String.String


fooField__Yafl__updateField_0 =
    Yafl.map2
        Foo__Yafl__updateField_0
        firstField__Yafl__updateField_0
        secondField__Yafl__updateField_0


firstField__Yafl__updateField_0 =
    Examples.fields.string |> Yafl.id "a-unique-string"


secondField__Yafl__updateField_0 =
    Examples.fields.string |> Yafl.id "another-unique-string"


model__Yafl__updateField_0 =
    fooField__Yafl__updateField_0 |> Yafl.init |> Tuple.first


updatedModel__Yafl__updateField_0 =
    model__Yafl__updateField_0
        |> Yafl.updateField firstField__Yafl__updateField_0 "Hello!"
        |> Tuple.first


form__Yafl__view_0 =
    Examples.fields.string


model__Yafl__view_0 =
    form__Yafl__view_0 |> Yafl.init |> Tuple.first
