module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Browser
import Examples
import Expect
import Html
import Html.Attributes
import Html.Events
import Platform.Cmd
import Platform.Sub
import Test
import Yafl


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Yafl.Widget () String.String String.String String.String
                            unused =
                                stringWidget__Readme_0
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        let
                            unused : Yafl.Widget () Basics.Int CounterMsg__Readme_0 Basics.Int
                            unused =
                                counterWidget__Readme_0
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 1"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused :
                                { string :
                                    Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String String.String
                                , counter :
                                    Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId Examples.CounterMsg Examples.CounterMsg Basics.Int
                                }
                            unused =
                                Examples.fields
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 2"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String String.String
                            unused =
                                Examples.nonEmptyString
                        in
                        Expect.pass
                    )
                , Test.test
                    "1"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String String.String
                            unused =
                                Examples.firstName
                        in
                        Expect.pass
                    )
                , Test.test
                    "2"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String String.String
                            unused =
                                Examples.lastName
                        in
                        Expect.pass
                    )
                , Test.test
                    "3"
                    (\() ->
                        let
                            unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId Examples.CounterMsg Examples.CounterMsg Basics.Int
                            unused =
                                Examples.numberOfPets
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 3"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused :
                                Yafl.Field
                                    Examples.FormModel
                                    Examples.FormMsg
                                    Yafl.NoId
                                    Basics.Never
                                    { firstName :
                                        Maybe.Maybe String.String
                                    , lastName : Maybe.Maybe String.String
                                    , numberOfPets : Maybe.Maybe Examples.CounterMsg
                                    }
                                    Examples.User
                            unused =
                                Examples.user
                        in
                        Expect.pass
                    )
                ]
            , Test.describe
                "code snippet 4"
                [ Test.test
                    "0"
                    (\() ->
                        let
                            unused : Platform.Program () (Yafl.Model Examples.FormModel Examples.User) (Yafl.Msg Examples.FormMsg)
                            unused =
                                main__Readme_4
                        in
                        Expect.pass
                    )
                ]
            ]
        , Test.describe
            "Yafl"
            [ Test.describe
                "module header"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : ( Yafl.Model Examples.FormModel Basics.Int, Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg) )
                                unused =
                                    init__Yafl__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            let
                                unused : List (Html.Html (Yafl.Msg Examples.FormMsg))
                                unused =
                                    Yafl.view
                                        form__Yafl__Header_0
                                        model__Yafl__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "2"
                        (\() ->
                            let
                                unused : Platform.Sub.Sub (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.subscriptions
                                        form__Yafl__Header_0
                                        model__Yafl__Header_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "3"
                        (\() ->
                            Yafl.submit
                                form__Yafl__Header_0
                                model__Yafl__Header_0
                                |> Expect.equal (Result.Ok 0)
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                myCustomTypeField__Yafl__Header_1
                                model__Yafl__Header_1
                                |> Expect.equal
                                    (Result.Ok (Foo__Yafl__Header_1 ""))
                        )
                    ]
                ]
            , Test.describe
                "andMap"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__andMap_0
                                model__Yafl__andMap_0
                                |> Expect.equal
                                    (Result.Ok
                                        { firstName = ""
                                        , middleName = ""
                                        , lastName = ""
                                        }
                                    )
                        )
                    ]
                ]
            , Test.describe
                "andThen"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String Basics.Float
                                unused =
                                    Examples.fields.string
                                        |> Yafl.label
                                            "Enter a floating-point number"
                                        |> Yafl.andThen
                                            (\string ->
                                                case String.toFloat string of
                                                    Maybe.Just float ->
                                                        Yafl.succeed float

                                                    Maybe.Nothing ->
                                                        Yafl.fail
                                                            "That's not a valid float"
                                            )
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String String.String
                                unused =
                                    Examples.fields.string
                                        |> Yafl.label
                                            "Enter the first name of a Beatle"
                                        |> Yafl.andThen
                                            (\name ->
                                                if
                                                    List.member
                                                        name
                                                        [ "John"
                                                        , "Paul"
                                                        , "George"
                                                        , "Ringo"
                                                        ]
                                                then
                                                    Yafl.succeed name

                                                else
                                                    Yafl.fail "Invalid Beatle"
                                            )
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "fail"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit form__Yafl__fail_0 model__Yafl__fail_0
                                |> Expect.equal
                                    (Result.Err [ ( "0", "Oh dear!" ) ])
                        )
                    ]
                ]
            , Test.describe
                "identifier"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String String.String
                                unused =
                                    myField__Yafl__identifier_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.HasId String.String String.String String.String
                                unused =
                                    myFieldWithId__Yafl__identifier_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "2"
                        (\() ->
                            let
                                unused : Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.send
                                        myFieldWithId__Yafl__identifier_0
                                        "Hello!"
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "init"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : ( Yafl.Model Examples.FormModel Basics.Int, Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg) )
                                unused =
                                    Examples.fields.counter |> Yafl.init
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "intercept"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused :
                                    Yafl.Msg Examples.FormMsg
                                    -> Maybe.Maybe String.String
                                unused =
                                    Yafl.intercept
                                        myFieldWithId__Yafl__intercept_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "label"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId String.String String.String String.String
                                unused =
                                    nameField__Yafl__label_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "load"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__load_0
                                modelBeforeLoading__Yafl__load_0
                                |> Expect.equal (Result.Ok 0)
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Yafl.submit
                                form__Yafl__load_0
                                modelAfterLoading__Yafl__load_0
                                |> Expect.equal (Result.Ok 1)
                        )
                    ]
                , Test.describe
                    "code snippet 1"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused :
                                    Yafl.Field
                                        Examples.FormModel
                                        Examples.FormMsg
                                        Yafl.NoId
                                        Basics.Never
                                        { a :
                                            Maybe.Maybe Examples.CounterMsg
                                        , b : Maybe.Maybe String.String
                                        }
                                        ( Basics.Int, String.String )
                                unused =
                                    form__Yafl__load_1
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Yafl.submit
                                form__Yafl__load_1
                                modelBeforeLoading__Yafl__load_1
                                |> Expect.equal (Result.Ok ( 0, "" ))
                        )
                    , Test.test
                        "2"
                        (\() ->
                            Yafl.submit
                                form__Yafl__load_1
                                modelAfterLoading__Yafl__load_1
                                |> Expect.equal (Result.Ok ( 0, "hello" ))
                        )
                    ]
                , Test.describe
                    "code snippet 2"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused :
                                    Yafl.Field
                                        Examples.FormModel
                                        Examples.FormMsg
                                        Yafl.NoId
                                        Basics.Never
                                        { selected :
                                            Maybe.Maybe Basics.Int
                                        , options :
                                            Maybe.Maybe
                                                { bar :
                                                    Maybe.Maybe Examples.CounterMsg
                                                , qux : Maybe.Maybe String.String
                                                }
                                        }
                                        Foo__Yafl__load_2
                                unused =
                                    form__Yafl__load_2
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            Yafl.submit
                                form__Yafl__load_2
                                modelBeforeLoading__Yafl__load_2
                                |> Expect.equal
                                    (Result.Ok (Bar__Yafl__load_2 0))
                        )
                    , Test.test
                        "2"
                        (\() ->
                            Yafl.submit
                                form__Yafl__load_2
                                modelAfterLoading__Yafl__load_2
                                |> Expect.equal
                                    (Result.Ok (Qux__Yafl__load_2 "hello"))
                        )
                    ]
                ]
            , Test.describe
                "map"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            fooField__Yafl__map_0
                                |> Yafl.init
                                |> Tuple.first
                                |> Yafl.submit fooField__Yafl__map_0
                                |> Expect.equal
                                    (Result.Ok (Foo__Yafl__map_0 ""))
                        )
                    ]
                ]
            , Test.describe
                "map2"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit form__Yafl__map2_0 model__Yafl__map2_0
                                |> Expect.equal (Result.Ok ( "", "" ))
                        )
                    ]
                ]
            , Test.describe
                "send"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Platform.Cmd.Cmd (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.send
                                        myFieldWithId__Yafl__send_0
                                        "Hello!"
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "submit"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__submit_0
                                model__Yafl__submit_0
                                |> Expect.equal (Result.Ok "")
                        )
                    ]
                ]
            , Test.describe
                "subscriptions"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Platform.Sub.Sub (Yafl.Msg Examples.FormMsg)
                                unused =
                                    Yafl.subscriptions
                                        form__Yafl__subscriptions_0
                                        model__Yafl__subscriptions_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "succeed"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__succeed_0
                                model__Yafl__succeed_0
                                |> Expect.equal (Result.Ok "Hurrah!")
                        )
                    ]
                ]
            , Test.describe
                "validate"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            form__Yafl__validate_0
                                |> Yafl.init
                                |> Tuple.first
                                |> Yafl.submit form__Yafl__validate_0
                                |> Expect.equal
                                    (Result.Err
                                        [ ( "0"
                                          , "Must be greater than 0, but the value is 0"
                                          )
                                        ]
                                    )
                        )
                    ]
                ]
            , Test.describe
                "validateAt"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            form__Yafl__validateAt_0
                                |> Yafl.init
                                |> Tuple.first
                                |> Yafl.load
                                    form__Yafl__validateAt_0
                                    { passwordField = Maybe.Just "password123"
                                    , confirmField = Maybe.Just "password124"
                                    }
                                |> Tuple.first
                                |> Yafl.submit form__Yafl__validateAt_0
                                |> Expect.equal
                                    (Result.Err
                                        [ ( "confirm"
                                          , "Passwords do not match"
                                          )
                                        ]
                                    )
                        )
                    ]
                ]
            , Test.describe
                "view"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : List (Html.Html (Yafl.Msg Examples.FormMsg))
                                unused =
                                    Yafl.view
                                        form__Yafl__view_0
                                        model__Yafl__view_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        ]


stringWidget__Readme_0 () =
    { init = ( "", Platform.Cmd.none )
    , update = \msg model -> ( msg, Platform.Cmd.none )
    , view =
        \{ label, id, feedback } model ->
            [ Html.label [ Html.Attributes.for id ] [ Html.text label ]
            , Html.input
                [ Html.Attributes.id id
                , Html.Attributes.type_ "text"
                , Html.Attributes.value model
                , Html.Events.onInput Basics.identity
                ]
                []
            , Html.ul [] (List.map (\f -> Html.li [] [ Html.text f ]) feedback)
            ]
    , subscriptions = \model -> Platform.Sub.none
    , submit = \model -> Result.Ok model
    , label = "String"
    }


type CounterMsg__Readme_0
    = Increment__Readme_0
    | Decrement__Readme_0


counterWidget__Readme_0 () =
    { init = ( 0, Platform.Cmd.none )
    , update =
        \msg model ->
            case msg of
                Increment__Readme_0 ->
                    ( model + 1, Platform.Cmd.none )

                Decrement__Readme_0 ->
                    ( model - 1, Platform.Cmd.none )
    , view =
        \{ label, id } model ->
            [ Html.label [ Html.Attributes.for id ] [ Html.text label ]
            , Html.fieldset
                [ Html.Attributes.id id ]
                [ Html.button
                    [ Html.Attributes.type_ "button"
                    , Html.Events.onClick Decrement__Readme_0
                    ]
                    [ Html.text "-" ]
                , Html.output [] [ Html.text (String.fromInt model) ]
                , Html.button
                    [ Html.Attributes.type_ "button"
                    , Html.Events.onClick Increment__Readme_0
                    ]
                    [ Html.text "+" ]
                ]
            ]
    , subscriptions = \_ -> Platform.Sub.none
    , submit = \model -> Result.Ok model
    , label = "Counter"
    }


fields__Readme_1 =
    Yafl.defineFields
        (\string counter -> { string = string, counter = counter })
        |> Yafl.addWidget Examples.stringWidget
        |> Yafl.addWidget Examples.counterWidget
        |> Yafl.endFields


type alias FormModel__Readme_1 =
    ( Maybe.Maybe String.String, ( Maybe.Maybe Basics.Int, () ) )


type alias FormMsg__Readme_1 =
    ( Maybe.Maybe String.String, ( Maybe.Maybe Examples.CounterMsg, () ) )


nonEmptyString__Readme_2 =
    Examples.fields.string
        |> Yafl.validate
            (\string ->
                if String.isEmpty string then
                    Maybe.Just "This field must not be blank"

                else
                    Maybe.Nothing
            )


firstName__Readme_2 =
    Examples.nonEmptyString |> Yafl.label "What is the user's first name?"


lastName__Readme_2 =
    Examples.nonEmptyString |> Yafl.label "What is the user's last name?"


numberOfPets__Readme_2 : Yafl.Field Examples.FormModel Examples.FormMsg Yafl.NoId Examples.CounterMsg Examples.CounterMsg Basics.Int
numberOfPets__Readme_2 =
    Examples.fields.counter |> Yafl.label "How many pets do they have?"


user__Readme_3 =
    Yafl.succeed Examples.User
        |> Yafl.andMap .firstName Examples.firstName
        |> Yafl.andMap .lastName Examples.lastName
        |> Yafl.andMap .numberOfPets Examples.numberOfPets


main__Readme_4 =
    Browser.element
        { init = \flags -> Yafl.init Examples.user
        , update = \msg model -> Yafl.update Examples.user msg model
        , view = \model -> Html.form [] (Yafl.view Examples.user model)
        , subscriptions = \model -> Yafl.subscriptions Examples.user model
        }


form__Yafl__Header_0 =
    Examples.fields.counter


init__Yafl__Header_0 =
    Yafl.init form__Yafl__Header_0


model__Yafl__Header_0 =
    Tuple.first init__Yafl__Header_0


type MyCustomType__Yafl__Header_1
    = Foo__Yafl__Header_1 String.String
    | Bar__Yafl__Header_1 Basics.Int


myCustomTypeField__Yafl__Header_1 =
    Yafl.choice
        |> Yafl.option "Foo" .foo fooField__Yafl__Header_1
        |> Yafl.option "Bar" .bar barField__Yafl__Header_1


fooField__Yafl__Header_1 =
    Examples.fields.string |> Yafl.map Foo__Yafl__Header_1


barField__Yafl__Header_1 =
    Examples.fields.counter |> Yafl.map Bar__Yafl__Header_1


model__Yafl__Header_1 =
    myCustomTypeField__Yafl__Header_1 |> Yafl.init |> Tuple.first


form__Yafl__andMap_0 =
    Yafl.succeed (\a b c -> { firstName = a, middleName = b, lastName = c })
        |> Yafl.andMap
            .firstName
            (Examples.fields.string |> Yafl.label "First name")
        |> Yafl.andMap
            .middleName
            (Examples.fields.string |> Yafl.label "Middle name")
        |> Yafl.andMap
            .lastName
            (Examples.fields.string |> Yafl.label "Last name")


model__Yafl__andMap_0 =
    Yafl.init form__Yafl__andMap_0 |> Tuple.first


form__Yafl__fail_0 =
    Yafl.fail "Oh dear!"


model__Yafl__fail_0 =
    form__Yafl__fail_0 |> Yafl.init |> Tuple.first


myField__Yafl__identifier_0 =
    Examples.fields.string


myFieldWithId__Yafl__identifier_0 =
    myField__Yafl__identifier_0
        |> Yafl.identifier "any-string-as-long-as-it's-unique"


myFieldWithId__Yafl__intercept_0 =
    Examples.fields.string
        |> Yafl.identifier "any-string-as-long-as-it's-unique"


nameField__Yafl__label_0 =
    Examples.fields.string |> Yafl.label "What is your name?"


form__Yafl__load_0 =
    Examples.fields.counter


modelBeforeLoading__Yafl__load_0 =
    form__Yafl__load_0 |> Yafl.init |> Tuple.first


modelAfterLoading__Yafl__load_0 =
    modelBeforeLoading__Yafl__load_0
        |> Yafl.load form__Yafl__load_0 Examples.Increment
        |> Tuple.first


form__Yafl__load_1 =
    Yafl.succeed (\int string -> ( int, string ))
        |> Yafl.andMap .a Examples.fields.counter
        |> Yafl.andMap .b Examples.fields.string


modelBeforeLoading__Yafl__load_1 =
    form__Yafl__load_1 |> Yafl.init |> Tuple.first


modelAfterLoading__Yafl__load_1 =
    modelBeforeLoading__Yafl__load_1
        |> Yafl.load
            form__Yafl__load_1
            { a = Maybe.Nothing, b = Maybe.Just "hello" }
        |> Tuple.first


type Foo__Yafl__load_2
    = Bar__Yafl__load_2 Basics.Int
    | Qux__Yafl__load_2 String.String


form__Yafl__load_2 =
    Yafl.choice
        |> Yafl.option "Bar" .bar barField__Yafl__load_2
        |> Yafl.option "Qux" .qux quxField__Yafl__load_2


barField__Yafl__load_2 =
    Yafl.map Bar__Yafl__load_2 Examples.fields.counter


quxField__Yafl__load_2 =
    Yafl.map Qux__Yafl__load_2 Examples.fields.string


modelBeforeLoading__Yafl__load_2 =
    form__Yafl__load_2 |> Yafl.init |> Tuple.first


modelAfterLoading__Yafl__load_2 =
    modelBeforeLoading__Yafl__load_2
        |> Yafl.load
            form__Yafl__load_2
            { selected = Maybe.Just 1
            , options =
                Maybe.Just { bar = Maybe.Nothing, qux = Maybe.Just "hello" }
            }
        |> Tuple.first


type MyCustomType__Yafl__map_0
    = Foo__Yafl__map_0 String.String


fooField__Yafl__map_0 =
    Yafl.map Foo__Yafl__map_0 Examples.fields.string


form__Yafl__map2_0 =
    Yafl.map2
        { input = \input -> ( Maybe.Nothing, Maybe.Nothing )
        , output = \a b -> ( a, b )
        }
        Examples.fields.string
        Examples.fields.string


model__Yafl__map2_0 =
    Yafl.init form__Yafl__map2_0 |> Tuple.first


myFieldWithId__Yafl__send_0 =
    Examples.fields.string
        |> Yafl.identifier "any-string-as-long-as-it's-unique"


form__Yafl__submit_0 =
    Examples.fields.string


model__Yafl__submit_0 =
    form__Yafl__submit_0 |> Yafl.init |> Tuple.first


form__Yafl__subscriptions_0 =
    Examples.fields.string


model__Yafl__subscriptions_0 =
    form__Yafl__subscriptions_0 |> Yafl.init |> Tuple.first


form__Yafl__succeed_0 =
    Yafl.succeed "Hurrah!"


model__Yafl__succeed_0 =
    form__Yafl__succeed_0 |> Yafl.init |> Tuple.first


form__Yafl__validate_0 =
    Yafl.succeed 0
        |> Yafl.validate
            (\int ->
                if int > 0 then
                    Maybe.Nothing

                else
                    Maybe.Just
                        ("Must be greater than 0, but the value is "
                            ++ String.fromInt int
                        )
            )


passwordField__Yafl__validateAt_0 =
    Examples.fields.string |> Yafl.identifier "password"


confirmField__Yafl__validateAt_0 =
    Examples.fields.string |> Yafl.identifier "confirm"


form__Yafl__validateAt_0 =
    Yafl.succeed
        (\password confirm -> { password = password, confirm = confirm })
        |> Yafl.andMap .passwordField passwordField__Yafl__validateAt_0
        |> Yafl.andMap .confirmField confirmField__Yafl__validateAt_0
        |> Yafl.validateAt
            confirmField__Yafl__validateAt_0
            (\{ password, confirm } ->
                if password == confirm then
                    Maybe.Nothing

                else
                    Maybe.Just "Passwords do not match"
            )


form__Yafl__view_0 =
    Examples.fields.string


model__Yafl__view_0 =
    form__Yafl__view_0 |> Yafl.init |> Tuple.first
