module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Expect
import Html
import Platform.Sub
import Test
import Yafl


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "Yafl"
            [ Test.describe
                "address"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field model msg Yafl.NoAddress Basics.Never ()
                                unused =
                                    myField__Yafl__address_0
                            in
                            Expect.pass
                        )
                    , Test.test
                        "1"
                        (\() ->
                            let
                                unused : Yafl.Field model msg Yafl.HasAddress Basics.Never ()
                                unused =
                                    myAddressedField__Yafl__address_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "andMap"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__andMap_0
                                model__Yafl__andMap_0
                                |> Expect.equal (Result.Ok { a = 1, b = 2 })
                        )
                    ]
                ]
            , Test.describe
                "fail"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit form__Yafl__fail_0 model__Yafl__fail_0
                                |> Expect.equal
                                    (Result.Err
                                        [ { message = "Oh dear!"
                                          , path = [ 0 ]
                                          , fail = Basics.True
                                          }
                                        ]
                                    )
                        )
                    ]
                ]
            , Test.describe
                "label"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Yafl.Field model msg Yafl.NoAddress Basics.Never ()
                                unused =
                                    myField__Yafl__label_0
                                        |> Yafl.label "This is my field"
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "map"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit form__Yafl__map_0 model__Yafl__map_0
                                |> Expect.equal (Result.Ok "True")
                        )
                    ]
                ]
            , Test.describe
                "map2"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit form__Yafl__map2_0 model__Yafl__map2_0
                                |> Expect.equal (Result.Ok { a = 1, b = 2 })
                        )
                    ]
                ]
            , Test.describe
                "submit"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__submit_0
                                model__Yafl__submit_0
                                |> Expect.equal (Result.Ok ())
                        )
                    ]
                ]
            , Test.describe
                "subscriptions"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : Platform.Sub.Sub (Yafl.Msg msg)
                                unused =
                                    Yafl.subscriptions
                                        form__Yafl__subscriptions_0
                                        model__Yafl__subscriptions_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            , Test.describe
                "succeed"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            Yafl.submit
                                form__Yafl__succeed_0
                                model__Yafl__succeed_0
                                |> Expect.equal (Result.Ok "Hurrah!")
                        )
                    ]
                ]
            , Test.describe
                "view"
                [ Test.describe
                    "code snippet 0"
                    [ Test.test
                        "0"
                        (\() ->
                            let
                                unused : List (Html.Html (Yafl.Msg msg))
                                unused =
                                    Yafl.view
                                        form__Yafl__view_0
                                        model__Yafl__view_0
                            in
                            Expect.pass
                        )
                    ]
                ]
            ]
        ]


myField__Yafl__address_0 =
    Yafl.succeed ()


myAddressedField__Yafl__address_0 =
    myField__Yafl__address_0 |> Yafl.address "any-string-as-long-as-it's-unique"


form__Yafl__andMap_0 =
    Yafl.succeed (\a b -> { a = a, b = b })
        |> Yafl.andMap (Yafl.succeed 1)
        |> Yafl.andMap (Yafl.succeed 2)


model__Yafl__andMap_0 =
    Yafl.init form__Yafl__andMap_0 |> Tuple.first


form__Yafl__fail_0 =
    Yafl.fail "Oh dear!"


model__Yafl__fail_0 =
    form__Yafl__fail_0 |> Yafl.init |> Tuple.first


myField__Yafl__label_0 =
    Yafl.succeed ()


form__Yafl__map_0 =
    Yafl.map
        (\bool ->
            if bool then
                "True"

            else
                "False"
        )
        (Yafl.succeed Basics.True)


model__Yafl__map_0 =
    Yafl.init form__Yafl__map_0 |> Tuple.first


form__Yafl__map2_0 =
    Yafl.map2 (\a b -> { a = a, b = b }) (Yafl.succeed 1) (Yafl.succeed 2)


model__Yafl__map2_0 =
    Yafl.init form__Yafl__map2_0 |> Tuple.first


form__Yafl__submit_0 =
    Yafl.succeed ()


model__Yafl__submit_0 =
    form__Yafl__submit_0 |> Yafl.init |> Tuple.first


form__Yafl__subscriptions_0 =
    Yafl.succeed ()


model__Yafl__subscriptions_0 =
    form__Yafl__subscriptions_0 |> Yafl.init |> Tuple.first


form__Yafl__succeed_0 =
    Yafl.succeed "Hurrah!"


model__Yafl__succeed_0 =
    form__Yafl__succeed_0 |> Yafl.init |> Tuple.first


form__Yafl__view_0 =
    Yafl.succeed ()


model__Yafl__view_0 =
    form__Yafl__view_0 |> Yafl.init |> Tuple.first
